name: Tauri Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'  # match your Node version
        cache: 'npm'

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Build frontend
      run: npm run build

    - name: Build Tauri app
      run: npx tauri build

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: tauri-build
        path: src-tauri/target/release/bundle/

